// src/partials/Home/Resource.jsx
import React, { useState, useRef, useEffect } from "react";
import Transition from "../../utils/Transition";

import Tab01 from "../../images/home/resource/1.webp";
import Tab02 from "../../images/home/resource/2.webp";
import Tab03 from "../../images/home/resource/3.webp";

function Resource() {
  const [tab, setTab] = useState(1);

  const tabs = useRef(null);

  const heightFix = () => {
    if (tabs.current.children[tab - 1]) {
      tabs.current.style.height =
        tabs.current.children[tab - 1].offsetHeight + "px";
    }
  };

  useEffect(() => {
    heightFix();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);

  return (
    <section className="relative">
      {/* Section background (needs .relative class on parent and next sibling elements) */}
      <div
        className="absolute inset-0 bg-gray-100 pointer-events-none mb-16"
        aria-hidden="true"
      ></div>

      <div id="how-to-work" className="relative max-w-6xl mx-auto px-4 sm:px-6">
        <div className="pt-12 md:pt-20">
          {/* Section content */}
          <div className="md:grid md:grid-cols-12 md:gap-6">
            {/* Content */}
            <div
              className="max-w-xl md:max-w-none md:w-full mx-auto md:col-span-7 lg:col-span-6 md:mt-6"
              data-aos="fade-right"
            >
              <div className="md:pr-4 lg:pr-12 xl:pr-16 mb-8">
                <h3 className="h3 mb-3">我们的资源优势</h3>
                <p className="text-xl text-gray-600">
                  和瑛社有各种各样的无论资金、人脉、技术以及实体设备资源，为社内项目的实施提供强有力的保障。
                </p>
              </div>
              {/* Tabs buttons */}
              <div className="mb-8 md:mb-0">
                <button
                  className={`flex items-center text-lg p-5 rounded border transition duration-300 ease-in-out mb-3 ${
                    tab !== 3
                      ? "bg-white shadow-md border-red-200 hover:shadow-lg"
                      : "bg-red-100 border-transparent"
                  }`}
                  onClick={(e) => {
                    e.preventDefault();
                    setTab(3);
                  }}
                >
                  <div>
                    <div className="font-bold leading-snug tracking-tight mb-1">
                      各领域杰出人才
                    </div>
                    <div className="text-gray-600">
                      服务器运维、三维建模、视频制作、音乐制作、文案编纂、配音……各方面杰出人才汇聚和瑛。
                    </div>
                  </div>
                  <div className="flex justify-center items-center w-8 h-8 bg-white text-red-600 rounded-full shadow shrink-0 ml-3">
                    <svg
                      className="w-3 h-3 fill-current"
                      viewBox="0 0 12 12"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M11.334 8.06a.5.5 0 00-.421-.237 6.023 6.023 0 01-5.905-6c0-.41.042-.82.125-1.221a.5.5 0 00-.614-.586 6 6 0 106.832 8.529.5.5 0 00-.017-.485z"
                        fillRule="nonzero"
                      />
                    </svg>
                  </div>
                </button>

                <button
                  className={`flex items-center text-lg p-5 rounded border transition duration-300 ease-in-out mb-3 ${
                    tab !== 1
                      ? "bg-white shadow-md border-red-200 hover:shadow-lg"
                      : "bg-red-100 border-transparent"
                  }`}
                  onClick={(e) => {
                    e.preventDefault();
                    setTab(1);
                  }}
                >
                  <div>
                    <div className="font-bold leading-snug tracking-tight mb-1">
                      稳定的服务器
                    </div>
                    <div className="text-gray-600">
                      以 Minecraft
                      为主题的和瑛社拥有高性能服务器用以支持中州纪元等多个 MC
                      服务器项目的运行。
                    </div>
                  </div>
                  <div className="flex justify-center items-center w-8 h-8 bg-white text-red-600 rounded-full shadow shrink-0 ml-3">
                    <svg
                      className="w-3 h-3 fill-current"
                      viewBox="0 0 12 12"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M11.953 4.29a.5.5 0 00-.454-.292H6.14L6.984.62A.5.5 0 006.12.173l-6 7a.5.5 0 00.379.825h5.359l-.844 3.38a.5.5 0 00.864.445l6-7a.5.5 0 00.075-.534z" />
                    </svg>
                  </div>
                </button>

                <button
                  className={`flex items-center text-lg p-5 rounded border transition duration-300 ease-in-out mb-3 ${
                    tab !== 2
                      ? "bg-white shadow-md border-red-200 hover:shadow-lg"
                      : "bg-red-100 border-transparent"
                  }`}
                  onClick={(e) => {
                    e.preventDefault();
                    setTab(2);
                  }}
                >
                  <div>
                    <div className="font-bold leading-snug tracking-tight mb-1">
                      高性能工作站
                    </div>
                    <div className="text-gray-600">
                      一台高性能工作站可以协助我们完成诸如 3D
                      渲染、航测计算、视频渲染等众多计算密集型繁重任务。
                    </div>
                  </div>
                  <div className="flex justify-center items-center w-8 h-8 bg-white text-red-600 rounded-full shadow shrink-0 ml-3">
                    <svg
                      className="w-3 h-3 fill-current"
                      viewBox="0 0 12 12"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M11.854.146a.5.5 0 00-.525-.116l-11 4a.5.5 0 00-.015.934l4.8 1.921 1.921 4.8A.5.5 0 007.5 12h.008a.5.5 0 00.462-.329l4-11a.5.5 0 00-.116-.525z"
                        fillRule="nonzero"
                      />
                    </svg>
                  </div>
                </button>
              </div>
            </div>

            {/* Tabs items */}
            <div
              className="max-w-xl md:max-w-none md:w-full mx-auto md:col-span-5 lg:col-span-6 mb-8 md:mb-0 md:order-1"
              data-aos="zoom-y-out"
              ref={tabs}
            >
              <div className="relative flex flex-col text-center lg:text-right">
                <Transition
                  show={tab === 3}
                  appear={true}
                  className="w-full"
                  enter="transition ease-in-out duration-700 transform order-first"
                  enterStart="opacity-0 translate-y-16"
                  enterEnd="opacity-100 translate-y-0"
                  leave="transition ease-in-out duration-300 transform absolute"
                  leaveStart="opacity-100 translate-y-0"
                  leaveEnd="opacity-0 -translate-y-16"
                >
                  <div className="relative inline-flex flex-col">
                    <img
                      className="md:max-w-none mx-auto rounded"
                      src={Tab03}
                      width="500"
                      height="375"
                      alt="Tab 03"
                    />
                  </div>
                </Transition>

                <Transition
                  show={tab === 1}
                  appear={true}
                  className="w-full"
                  enter="transition ease-in-out duration-700 transform order-first"
                  enterStart="opacity-0 translate-y-16"
                  enterEnd="opacity-100 translate-y-0"
                  leave="transition ease-in-out duration-300 transform absolute"
                  leaveStart="opacity-100 translate-y-0"
                  leaveEnd="opacity-0 -translate-y-16"
                >
                  <div className="relative inline-flex flex-col">
                    <img
                      className="md:max-w-none mx-auto rounded"
                      src={Tab01}
                      width="500"
                      height="375"
                      alt="Tab 01"
                    />
                  </div>
                </Transition>

                <Transition
                  show={tab === 2}
                  appear={true}
                  className="w-full"
                  enter="transition ease-in-out duration-700 transform order-first"
                  enterStart="opacity-0 translate-y-16"
                  enterEnd="opacity-100 translate-y-0"
                  leave="transition ease-in-out duration-300 transform absolute"
                  leaveStart="opacity-100 translate-y-0"
                  leaveEnd="opacity-0 -translate-y-16"
                >
                  <div className="relative inline-flex flex-col">
                    <img
                      className="md:max-w-none mx-auto rounded"
                      src={Tab02}
                      width="500"
                      height="375"
                      alt="Tab 02"
                    />
                  </div>
                </Transition>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default Resource;

// components/index/Resource.vue
<template>
  <section class="relative">
    <!-- Section background (needs .relative class on parent and next sibling elements) -->
    <div
      class="absolute inset-0 bg-gray-100 pointer-events-none mb-16"
      aria-hidden="true"
    ></div>

    <div id="how-to-work" class="relative max-w-6xl mx-auto px-4 sm:px-6">
      <div class="pt-12 md:pt-20">
        <div class="md:grid md:grid-cols-12 md:gap-6">
          <div
            class="max-w-xl md:max-w-none md:w-full mx-auto md:col-span-7 lg:col-span-6 md:mt-6"
            data-aos="fade-right"
          >
            <div class="md:pr-4 lg:pr-12 xl:pr-16 mb-8">
              <h3 class="h3 mb-3">我们的资源优势</h3>
              <p class="text-xl text-gray-600">
                和瑛社有各种各样的无论资金、人脉、技术以及实体设备资源，为社内项目的实施提供强有力的保障。
              </p>
            </div>
            <div class="mb-8 md:mb-0">
              <button
                v-for="(i, index) in tabContent"
                :key="i.title"
                :class="`flex items-center text-lg p-5 rounded border transition duration-300 ease-in-out mb-3
                  ${
                    currentTab !== index
                      ? 'bg-white shadow-md border-red-200 hover:shadow-lg'
                      : 'bg-red-100 border-transparent'
                  }`"
                @click="
                  (e) => {
                    currentTab = index
                  }
                "
              >
                <div>
                  <div class="font-bold leading-snug tracking-tight mb-1">
                    {{ i.title }}
                  </div>
                  <div class="text-gray-600">
                    {{ i.text }}
                  </div>
                </div>
                <div
                  class="flex justify-center items-center w-8 h-8 bg-white text-red-600 rounded-full shadow shrink-0 ml-3"
                  v-html="i.icon"
                ></div>
              </button>
            </div>
          </div>

          <div
            class="max-w-xl md:max-w-none md:w-full mx-auto md:col-span-5 lg:col-span-6 mb-8 md:mb-0 md:order-1"
            data-aos="zoom-y-out"
          >
            <div class="relative flex flex-col text-center lg:text-right">
              <Transition
                v-for="(i, index) in tabContent"
                :key="i.title"
                class="w-full"
                enter-active-class="transition ease-in-out duration-700 transform order-first"
                enter-from-class="opacity-0 translate-y-16"
                enter-to-class="opacity-100 translate-y-0"
                leave-active-class="transition ease-in-out duration-300 transform absolute"
                leave-from-class="opacity-100 translate-y-0"
                leave-to-class="opacity-0 -translate-y-16"
              >
                <div
                  class="relative inline-flex flex-col"
                  v-show="currentTab == index"
                >
                  <img
                    class="md:max-w-none mx-auto rounded"
                    :src="i.img"
                    width="500"
                    height="375"
                    alt="Tab 03"
                  />
                </div>
              </Transition>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import icons from 'assets/icons/index/resource'
import Tab01 from 'assets/images/index/resource/3.webp'
import Tab02 from 'assets/images/index/resource/1.webp'
import Tab03 from 'assets/images/index/resource/2.webp'

const currentTab = ref(0)

const tabContent = [
  {
    title: '各领域杰出人才',
    text: '服务器运维、三维建模、视频制作、音乐制作、文案编纂、配音……各方面杰出人才汇聚和瑛。',
    icon: icons.moon,
    img: Tab01,
  },
  {
    title: '稳定的服务器',
    text: '以 Minecraft 为主题的和瑛社拥有高性能服务器用以支持中州纪元等多个 MC 服务器项目的运行。',
    icon: icons.thunder,
    img: Tab02,
  },
  {
    title: '高性能工作站',
    text: '一台高性能工作站可以协助我们完成诸如 3D 渲染、航测计算、视频渲染等众多计算密集型繁重任务。',
    icon: icons.arrow,
    img: Tab03,
  },
]
</script>
